# Generated by Django 4.0.4 on 2022-05-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_for',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(choices=[('1000 To 10000', '1000 To 10000'), ('10 To 100', '10 To 100'), ('10000 To 20000', '10000 To 20000'), ('100 To 1000', '100 To 1000')], max_length=100),
        ),
    ]
