# Generated by Django 4.0.4 on 2022-05-19 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filter_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(choices=[('10 To 100', '10 To 100'), ('1000 To 10000', '1000 To 10000'), ('10000 To 20000', '10000 To 20000'), ('100 To 1000', '100 To 1000')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
