# Generated by Django 4.0.4 on 2022-05-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_price_price_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(choices=[('10000 To 20000', '10000 To 20000'), ('10 To 100', '10 To 100'), ('100 To 1000', '100 To 1000'), ('1000 To 10000', '1000 To 10000')], max_length=100),
        ),
    ]
