# Generated by Django 4.0.4 on 2022-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_alter_price_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='banner')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero')),
            ],
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(choices=[('1000 To 10000', '1000 To 10000'), ('100 To 1000', '100 To 1000'), ('10000 To 20000', '10000 To 20000'), ('10 To 100', '10 To 100')], max_length=100),
        ),
    ]
