# Generated by Django 4.0.4 on 2022-05-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_banner_hero_alter_price_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=400)),
                ('token', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(choices=[('100 To 1000', '100 To 1000'), ('1000 To 10000', '1000 To 10000'), ('10 To 100', '10 To 100'), ('10000 To 20000', '10000 To 20000')], max_length=100),
        ),
    ]
