# Generated by Django 4.0.4 on 2022-05-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_order_alter_price_price_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(choices=[('100 To 1000', '100 To 1000'), ('10 To 100', '10 To 100'), ('10000 To 20000', '10000 To 20000'), ('1000 To 10000', '1000 To 10000')], max_length=100),
        ),
    ]
