# Generated by Django 4.0.4 on 2022-05-22 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_rename_laststname_order_lastname_alter_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(choices=[('1000 To 10000', '1000 To 10000'), ('10 To 100', '10 To 100'), ('10000 To 20000', '10000 To 20000'), ('100 To 1000', '100 To 1000')], max_length=100),
        ),
    ]
